### ISSUE TITLE
Setting as "default"?

### ISSUE THREAD

**Issue by mightyiam** [danielb2/purdy.js#43]
Is there a way to have anything printed from node go through this?

Are there cons to that?

**Comment by danielb2** [comment]
Not in any way that I can think of. The con would be that it's more resource intensive than using console.log. Also since I'm using console.log under the hood you can't override that, and even if you could, they don't take the same parameters. 

However, I suppose I could change all calls to console.log to use process.stdout.write instead and change the arguments to be the same.

That way you could in theory do `console.log = Purdy` and use it that way

**Comment by mightyiam** [comment]
I'm concerned that bypassing `console.log` by using `process.stdout.write` could have some unintended effects.

Perhaps replacing the globally available `console.log` with Purdy while internally using a reference to it?

`replace.js`
``` js
const purdy = require('.')

let realConsoleLog
if (realConsoleLog !== console.log) {
  realConsoleLog = console.log
  console.log = purdy
}

module.exports = realConsoleLog
```

And inside purdy you could do
```
const realConsoleLog = require('./replace') || console.log
// and use it
```

Using [`node --require purdy/replace`](https://nodejs.org/api/cli.html#cli_r_require_module) then, you could have a kind of transparent replacement.

Further, one could shell alias node to have that `--require`...

**Comment by mightyiam** [comment]
Here's #44.

**Comment by danielb2** [comment]
only action here is to replace console.log with process.stdout.write in which case it will allow you to overwrite console.log later
